version: '3'

services:

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    expose:
      - 5000
    ports:
      - "5000:5000"
    links:  
      - mongo_db:mongo_db
      - elasticsearch:elasticsearch
    depends_on:
      - mongo_db
      - elasticsearch
    restart: always  
    volumes:
      - ./backend/codes:/usr/src/app
    command: gunicorn -w 1 -b 0.0.0.0:5000 -t 240 wsgi:app 
    stdin_open: true
    tty: true
    
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    expose:
      - 3000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
#     stdin_open: true
#     tty: true
    restart: always
  
  mongo_db:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - ./mongo/db:/data/db
    ports:
      - "27017:27017"

  mongo-seed: # 현재 다시 사용 (한번 실행 후에는 꼭 주석처리)
    build: ./mongo-seed
    links:
      - mongo_db

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    restart: "on-failure"

  elasticsearch:
    build: 
      context: ./ELK/elasticsearch/
      dockerfile: elastic.Dockerfile
    volumes:
      - type: bind
        source: ./ELK/elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "XPACK_SECURITY_ENABLED=false"
  # kibana:
  #   build:
  #     context: ./ELK/kibana/
  #     dockerfile: kibana.Dockerfile
  #   volumes:
  #     - type: bind
  #       source: ./ELK/kibana/config/kibana.yml
  #       target: /usr/share/kibana/config/kibana.yml
  #       read_only: true
  #   ports:
  #     - "5601:5601"
  #   depends_on:
  #     - elasticsearch

  # logstash:
  #   build:
  #     context: ./ELK/logstash/
  #     dockerfile: logstash.Dockerfile
  #   volumes:
  #     - type: bind
  #       source: ./ELK/logstash/config/logstash.yml
  #       target: /usr/share/logstash/config/logstash.yml
  #       read_only: true
  #     - type: bind
  #       source: ./ELK/logstash/pipeline
  #       target: /usr/share/logstash/pipeline
  #       read_only: true
  #   ports:
  #     - "5001:5001/tcp"
  #     - "5001:5001/udp"
  #     - "9600:9600"
  #   environment:
  #     LS_JAVA_OPTS: "-Xmx256m -Xms256m"
  #   depends_on:
  #     - elasticsearch
  #   restart: always  

  prometheus:
    image: prom/prometheus:latest
    user: root
    volumes:
      - ./prometheus/:/etc/prometheus/
      - ./prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    restart: always

  grafana:
    image: grafana/grafana
    user: root
    depends_on:
      - prometheus
    ports:
      - 3001:3000
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    restart: always
